# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: shanepaper/autoversion
  username: shanepaper
  password: $DOCKER_PW
  email: shane@get-paper.com

definitions:
  steps:
    - step: &run-tests
        name: Run Tests
        caches:
          - node
        script:
          - npm install
          - npm run test
    - step: &up-develop
        name: Up Develop
        caches:
          - node
        script:
          # HTTPS METHOD
          # PACKAGE INSTALLATIONS
          - npm install
          - npm install -g gulp
          # AUTO VERSIONING
          - npm run tag:develop
          # GIT COMMANDS
          - bash ./scripts/git.sh
    - step: &up-patch
        name: Up Patch
        caches:
          - node
        script:
          # HTTPS METHOD
          # PACKAGE INSTALLATIONS
          - npm install
          - npm install -g gulp
          # AUTO VERSIONING
          - npm run tag:patch
            # GIT COMMANDS
          - bash ./scripts/git.sh
    - step: &up-minor
        name: Up Minor
        caches:
          - node
        script:
          # HTTPS METHOD
          # PACKAGE INSTALLATIONS
          - npm install
          - npm install -g gulp
          # AUTO VERSIONING
          - npm run tag:minor
            # GIT COMMANDS
          - bash ./scripts/git.sh
    - step: &up-major
        name: Up Major
        caches:
          - node
        script:
          # HTTPS METHOD
          # PACKAGE INSTALLATIONS
          - npm install
          - npm install -g gulp
          # AUTO VERSIONING
          - npm run tag:major
            # GIT COMMANDS
          - bash ./scripts/git.sh

pipelines:
  default:
    - step: *run-tests
  branches:
    develop:
      - step: *up-develop
    master:
      - step: *up-patch
# # SSH METHOD - TODO: connect with ssh - replaces https method
#         script:
#           - touch ~/.ssh/my_ssh_key.pub
#           - cat pipelines_ssh_key.pub >> ~/.ssh/my_ssh_key.pub
#           - cat ~/.ssh/my_ssh_key.pub
#           - chmod 600 ~/.ssh/*

#           - ssh -v -i ~/.ssh/my_ssh_key.pub git@bitbucket.org
#           - declare -x VERSION=$(jq '.version' package.json)
#           - echo $VERSION;
#           - git tag 'test_tag3'
#           - git push --tags
