# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:15.12.0

pipelines:
  default:
    - step:
        script:
          # PACKAGE INSTALLATIONS
          - npm install
  branches:
    develop:
      - step:
          script:
            # HTTPS METHOD
            # PACKAGE INSTALLATIONS
            - npm install
            - npm install -g gulp
            - npm run tag:develop
            # AUTO VERSIONING
            - bash ./scripts/git.sh
    master:
      - step:
          script:
            # HTTPS METHOD
            # PACKAGE INSTALLATIONS
            - npm install
            - npm install -g gulp
            - npm run tag:patch
            # AUTO VERSIONING
            - bash ./scripts/git.sh
# # SSH METHOD - TODO: connect with ssh - replaces https method
#         script:
#           - touch ~/.ssh/my_ssh_key.pub
#           - cat pipelines_ssh_key.pub >> ~/.ssh/my_ssh_key.pub
#           - cat ~/.ssh/my_ssh_key.pub
#           - chmod 600 ~/.ssh/*

#           - ssh -v -i ~/.ssh/my_ssh_key.pub git@bitbucket.org
#           - declare -x VERSION=$(jq '.version' package.json)
#           - echo $VERSION;
#           - git tag 'test_tag3'
#           - git push --tags
